# Configuration de protection de branche
branch-protection:
  main:
    # Nombre de revues requises
    required_pull_request_reviews:
      required_approving_review_count: 1

    # Vérifications requises
    required_status_checks:
      strict: true
      contexts:
        - ci/tests
        - code-review

    # Restrictions
    enforce_admins: true
    restrict_pushes:
      enabled: true